# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heektime-schema/services/lectures.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from heektime_schema import lecture_pb2 as heektime__schema_dot_lecture__pb2
from heektime_schema import period_pb2 as heektime__schema_dot_period__pb2
from heektime_schema import semester_pb2 as heektime__schema_dot_semester__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'heektime-schema/services/lectures.proto\x12\rheek.heektime\x1a\x1dheektime-schema/lecture.proto\x1a\x1cheektime-schema/period.proto\x1a\x1eheektime-schema/semester.proto\"\xe9\x01\n\x12GetLecturesPayload\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12)\n\x08semester\x18\x02 \x01(\x0e\x32\x17.heek.heektime.Semester\x12\x11\n\tschool_id\x18\x03 \x01(\t\x12&\n\x07periods\x18\x07 \x03(\x0b\x32\x15.heek.heektime.Period\x12\x39\n\x07options\x18\n \x03(\x0b\x32(.heek.heektime.GetLecturesPayload.Option\x1a$\n\x06Option\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2X\n\x08Lectures\x12L\n\x0bGetLectures\x12!.heek.heektime.GetLecturesPayload\x1a\x16.heek.heektime.Lecture\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heektime_schema.services.lectures_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETLECTURESPAYLOAD._serialized_start=152
  _GETLECTURESPAYLOAD._serialized_end=385
  _GETLECTURESPAYLOAD_OPTION._serialized_start=349
  _GETLECTURESPAYLOAD_OPTION._serialized_end=385
  _LECTURES._serialized_start=387
  _LECTURES._serialized_end=475
# @@protoc_insertion_point(module_scope)
