# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heektime-schema/semester.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eheektime-schema/semester.proto\x12\rheek.heektime*E\n\x08Semester\x12\x0b\n\x07unknown\x10\x00\x12\n\n\x06spring\x10\x01\x12\n\n\x06summer\x10\x02\x12\x08\n\x04\x66\x61ll\x10\x03\x12\n\n\x06winter\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heektime_schema.semester_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEMESTER._serialized_start=49
  _SEMESTER._serialized_end=118
# @@protoc_insertion_point(module_scope)
